package io.github.tuguzd.restaurantapp.domain.model.util

import io.github.tuguzd.restaurantapp.domain.util.randomNanoId
import kotlinx.serialization.Serializable

/**
 * NanoID generated by [randomNanoId] function.
 */
@JvmInline
@Serializable
public value class NanoId(private val value: String) {
    override fun toString(): String = value
}
